# Generated by Django 4.1.3 on 2023-11-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_blogcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='parent',
        ),
    ]
